// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GestionStock.Models
{
    public partial class Item
    {
        public int Id { get; set; }
        public string Marque { get; set; }
        public string Designation { get; set; }
        public string Reference { get; set; }
        public int? Quantity { get; set; }
    }
}